# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for installing dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

FROM node:18-alpine AS release

# Set working directory
WORKDIR /app

# Copy the build artifacts and node_modules from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Specify environment variables (these should be set to the base64 encoded strings of your credentials)
ENV GOOGLE_CREDENTIALS=your_base64_encoded_credentials_here
ENV GOOGLE_TOKEN=your_base64_encoded_token_here

# Start the application
ENTRYPOINT ["node", "build/index.js"]